### ISSUE TITLE
服务器和客户端都启动失败。

### ISSUE THREAD

**Issue by lishiwei** [mcuking/offline-package-admin#4]
服务器和客户端都启动失败。
![image](https://user-images.githubusercontent.com/6994148/195576500-c991f836-b312-4a22-a521-0ded38677857.png)
![image](https://user-images.githubusercontent.com/6994148/195576748-0b879c62-641c-4657-a7b6-0de1a9289bd5.png)

**Comment by mcuking** [comment]
@lishiwei 更新下全局安装的 typescript 版本即可
